name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: ["Debug", "Release", "MinSizeRel", "RelWithDebInfo"]
        compiler:
          - { cc: "gcc", cxx: "g++" }
          - { cc: "clang", cxx: "clang++" }

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/cache
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
        shell: bash

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: dependencies
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Install dependencies
        run: sudo bash script/build.sh

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DKLIB_BUILD_TEST=ON -DKLIB_BUILD_EXTRA_TEST=${{ matrix.build_type == 'Release' }}
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j"$(nproc)"

      - name: Install
        if: ${{ matrix.build_type == 'Release' }}
        run: |
          sudo cmake --build build --config ${{ matrix.build_type }} --target install
          sudo ldconfig

      - name: Test
        run: cd build ; ctest -C ${{ matrix.build_type }} -j"$(nproc)" --output-on-failure

      - name: Uninstall
        if: ${{ matrix.build_type == 'Release' }}
        run: sudo cmake --build build --config ${{ matrix.build_type }} --target uninstall
