name: Release

on:
  push:
    branches: [ "main" ]
    tags:
        - vf*
  pull_request:
    branches: [ "main" ]
  release:
    # https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kaiserlancelot/kenv:latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j"$(nproc)"

      - name: CPack
        run: cpack
        working-directory: build

      - name: Install
        run: sudo dpkg -i klib*.deb
        working-directory: build
      
      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: release-dist
          path: |
              build/klib*.tar.xz
              build/klib*.deb
