name: Release

on:
  release:
    # https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published
    types: [published]

jobs:
  build:
    # https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - { cc: "gcc", cxx: "g++" }
          - { cc: "clang", cxx: "clang++" }

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/cache
      - name: Get date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: dependencies
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Install dependencies
        run: sudo bash script/build.sh

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release -j"$(nproc)"

      # https://github.community/t/how-to-get-just-the-tag-name/16241/10
      - name: Get version
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}
        shell: bash

      - name: CPack
        run: |
          cpack
          mv klib-${{ steps.get-version.outputs.version }}-Linux.deb \
          klib-${{ steps.get-version.outputs.version }}-ubuntu-20.04.deb
          mv klib-${{ steps.get-version.outputs.version }}-Linux.tar.gz \
          klib-${{ steps.get-version.outputs.version }}-ubuntu-20.04.tar.gz
        working-directory: build

      - name: Install
        run: |
          sudo dpkg -i klib-${{ steps.get-version.outputs.version }}-ubuntu-20.04.deb
          sudo ldconfig
        working-directory: build

      - name: Build example
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j"$(nproc)"
        working-directory: example
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.compiler.cxx == 'g++' }}
        with:
          files: |
            build/klib-${{ steps.get-version.outputs.version }}-ubuntu-20.04.deb
            build/klib-${{ steps.get-version.outputs.version }}-ubuntu-20.04.tar.gz
